feat(seeMoreList): dev complete code + unit tests - EHF-13863
evdy-consumer/component-react-see-more-list pull request #1
Opened 2020-09-18 23:47 UTC by clucaseh

feat(seeMoreList): dev complete code + unit tests - EHF-13863

 - re-useable component to handle splitting a list into multiple chunks. Showing the first one and hiding the remaining for SEO purposes. 
 - accepts a prop `renderItem` which is a function that renders the HTML from the parent component. 
 - accepts a prop `chunkGroupSize` which is an integer. The list will be broken into chunks defined by the size here.
 - accepts a prop `customChunkGroupSizes` which is an array of chunkSizes. The groups will be chunked by the size you define. With the last being used for the remaining items.

For instance if you pass `[3,5]` and you have an array of 18 items. Your list chunk groups would be  3, 5, 5, 5
For instance if you pass `[3,4,5]` and you have an array of 18 items. Your list chunk groups would be  3, 4, 5, 5, 1

2020-09-22 12:54 UTC, kzusy requested changes

2020-09-22 12:54 UTC, kzusy commented on package.json
> +    "@evdy-consumer/component-react-buttons": "^0.2.0",
These are used by the component so should be included in dependencies as opposed to devDependencies

- [ ] Update

2020-09-22 12:54 UTC, kzusy commented on src/component.scss
> +    top: -9999px;
Why hiding this way instead of just using display none?

2020-09-22 12:54 UTC, kzusy commented on src/index.js
> +    this.chunkGroups = this.getItemsChunkedIntoGroups(props.items);
This is an anti pattern. We should avoid setting instance variables based on prop values in the constructor. Instead use memoization (you can make use of lodash's memoize function) when calling getItemsChunkedIntoGroups() so that calling it more than once with the same arguments will return the same value each time without doing additional work

- [ ] Update

2020-09-22 12:54 UTC, kzusy commented on src/index.js
> +    remainingItems = chunk(
Using `chunk()` here seems extraneous. Since you're on the last index of customChunkGroupSizes, couldn't you just get that last size and then do an items.slice() to get the last chunk?

2020-09-22 12:54 UTC, kzusy commented on src/index.js
> +        activeChunk,
Might be a good idea to also include the rest of the previous state, just in case you add additional state properties in the future, that you dont' want to get accidentally wiped:

```js
this.setState((prevState) => {
  const activeChunk = prevState.activeChunk + 1;

  return {
    ...prevState,
    activeChunk,
    visibleChunks: {
      ...prevState.visibleChunks,
      [activeChunk]: true
    }
  };
});
```

2020-09-22 12:54 UTC, kzusy commented on src/index.js
> +    return (
can we add a newline between the variable declaration above and the return statement?

2020-09-22 13:01 UTC, clucaseh commented on src/component.scss
> +    top: -9999px;
For accessibility readers. The content with display: none will not be read. Also read its slightly better for performance. 
https://www.sitepoint.com/hide-elements-in-css/

Can maybe switch to transform for even better performance maybe

2020-09-22 13:21 UTC, sblashkin commented on package.json
> +    "@evdy-consumer/component-react-buttons": "^0.2.0",
could you pls use staging6 version?

2020-09-22 15:51 UTC, clucaseh commented on src/index.js
> +    remainingItems = chunk(
Since when on last index I do want to make multiple chunks and not just one chunk() fits best here

2020-09-22 15:59 UTC, kzusy commented on src/component.scss
> +    top: -9999px;
Do we want accessibility readers to be able to read the content before the user hits the see more button?

2020-09-22 16:05 UTC, kzusy requested changes

2020-09-22 16:05 UTC, kzusy commented on src/index.js
> +    const chunkGrouper = memoize(items => this.getItemsChunkedIntoGroups(items));
You could also just do `this.getItemsChunkedIntoGroups = memoize(this.getItemsChunkedIntoGroups)`, as long as you update that method to bind to the instance. That way you don't have to create another instance variable

2020-09-22 16:05 UTC, kzusy commented on src/index.js
> +    this.chunkGroups = chunkGrouper(props.items);
The idea is to avoid setting an instance variable from props in the constructor. This is still doing that

- [ ] Don't set an instance variable from props in the constructor

2020-09-22 17:39 UTC, kzusy approved these changes

2020-09-22 17:42 UTC, sblashkin approved these changes

2020-09-22 17:53 UTC, merged

2020-09-28 21:23 UTC, kzusy commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@evdy-consumer/component-react-see-more-list/v/1.0.0)
- [GitHub release](https://github.com/evdy-consumer/component-react-see-more-list/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: